# Generated by Django 5.2.8 on 2025-11-21 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AliceTant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='provider_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.CharField(help_text='Name of the business', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Business description (max 4096 characters)', max_length=4096)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Business address')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'alicetant_provider',
            },
        ),
    ]
