# Generated by Django 5.2.8 on 2025-11-21 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AliceTant', '0002_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(help_text="Customer's full name", max_length=200)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('preferences', models.TextField(blank=True, help_text='Optional customer preferences for appointments')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'alicetant_customer',
            },
        ),
    ]
