# Generated by Django 5.2.8 on 2025-12-04 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AliceTant', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the business/service', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the business', max_length=2000)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('address', models.TextField(help_text='Physical address of the business')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the business was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the business was last updated')),
                ('provider', models.ForeignKey(help_text='Provider who owns this business', on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='AliceTant.provider')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'db_table': 'alicetant_business',
                'ordering': ['-created_at'],
            },
        ),
    ]
