# Generated by Django 5.2.8 on 2025-12-04 05:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AliceTant', '0004_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], help_text='Day of week (0=Sunday, 6=Saturday)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('start_time', models.TimeField(help_text='Start time of availability window')),
                ('end_time', models.TimeField(help_text='End time of availability window')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the availability was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the availability was last updated')),
                ('business', models.ForeignKey(help_text='Business this availability applies to', on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='AliceTant.business')),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availabilities',
                'db_table': 'alicetant_availability',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('business', 'day_of_week', 'start_time')},
            },
        ),
    ]
