# Generated by Django 5.2.8 on 2025-12-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AliceTant', '0005_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, help_text='Business logo image', null=True, upload_to='business_logos/'),
        ),
        migrations.AddField(
            model_name='business',
            name='summary',
            field=models.CharField(blank=True, help_text='Brief description of the business (max 512 characters)', max_length=512),
        ),
    ]
