# Generated by Django 5.2.8 on 2025-12-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AliceTant', '0006_business_logo_business_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(help_text='Date of the appointment')),
                ('appointment_time', models.TimeField(help_text='Time of the appointment')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', help_text='Current status of the appointment', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the appointment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when appointment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when appointment was last updated')),
                ('business', models.ForeignKey(help_text='Business where the appointment is scheduled', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='AliceTant.business')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'alicetant_appointment',
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when customer was added to appointment')),
                ('appointment', models.ForeignKey(help_text='Appointment being linked', on_delete=django.db.models.deletion.CASCADE, to='AliceTant.appointment')),
                ('customer', models.ForeignKey(help_text='Customer being linked', on_delete=django.db.models.deletion.CASCADE, to='AliceTant.customer')),
            ],
            options={
                'verbose_name': 'Appointment Customer',
                'verbose_name_plural': 'Appointment Customers',
                'db_table': 'alicetant_appointment_customer',
                'unique_together': {('appointment', 'customer')},
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='customers',
            field=models.ManyToManyField(help_text='Customers associated with this appointment', related_name='appointments', through='AliceTant.AppointmentCustomer', to='AliceTant.customer'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['business', 'appointment_date', 'appointment_time'], name='alicetant_a_busines_d6f98c_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'status'], name='alicetant_a_appoint_e4ab0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('business', 'appointment_date', 'appointment_time'), name='unique_active_appointment_slot'),
        ),
    ]
