# Generated by Django 5.2.8 on 2026-04-25 04:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AliceTant', '0007_appointment_appointmentcustomer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='AliceTant.business')),
            ],
            options={
                'verbose_name': 'Business Closure',
                'verbose_name_plural': 'Business Closures',
                'db_table': 'alicetant_business_closure',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False, help_text='If True, the business is closed all day on this day.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='AliceTant.business')),
            ],
            options={
                'verbose_name': 'Working Hours',
                'verbose_name_plural': 'Working Hours',
                'db_table': 'alicetant_working_hours',
                'ordering': ['day_of_week', 'open_time'],
                'unique_together': {('business', 'day_of_week')},
            },
        ),
    ]
