# Generated by Django 5.2.8 on 2026-04-25 05:12

from django.db import migrations, models


def merge_description_into_summary(apps, schema_editor):
    """Copy description content into summary for existing businesses."""
    Business = apps.get_model('AliceTant', 'Business')
    for biz in Business.objects.all():
        parts = []
        if biz.summary:
            parts.append(biz.summary)
        if biz.description:
            parts.append(biz.description)
        biz.summary = '\n\n'.join(parts)[:4096]
        biz.save(update_fields=['summary'])


class Migration(migrations.Migration):

    dependencies = [
        ('AliceTant', '0008_working_hours_and_closures'),
    ]

    operations = [
        # First widen summary to accept more text
        migrations.AlterField(
            model_name='business',
            name='summary',
            field=models.TextField(blank=True, help_text='Description / summary of the business (max 4096 characters)', max_length=4096),
        ),
        # Merge existing description into summary
        migrations.RunPython(merge_description_into_summary, migrations.RunPython.noop),
        # Now safe to remove description
        migrations.RemoveField(
            model_name='business',
            name='description',
        ),
        migrations.AddField(
            model_name='businessclosure',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=200),
        ),
    ]
