# Generated by Django 5.2.8 on 2026-04-25 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AliceTant', '0009_merge_description_into_summary_and_closure_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_active_appointment_slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='availability',
            field=models.ForeignKey(blank=True, help_text='The availability slot this appointment was booked against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='AliceTant.availability'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time of the appointment', null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Max concurrent bookings. NULL means 1 (single booking at a time).', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(help_text='Start time of the appointment'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['availability', 'appointment_date', 'status'], name='alicetant_a_availab_f2521b_idx'),
        ),
    ]
