# Generated by Django 5.2.8 on 2026-04-25 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AliceTant', '0011_availability_date_and_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], help_text='Day of week (0=Sunday, 6=Saturday), auto-derived from date', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
