# Generated by Django 5.2.8 on 2026-04-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AliceTant', '0013_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reference_id',
            field=models.PositiveIntegerField(editable=False, help_text='Unique 8-digit reference ID for display', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='business',
            name='reference_id',
            field=models.PositiveIntegerField(editable=False, help_text='Unique 8-digit reference ID for display', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reference_id',
            field=models.PositiveIntegerField(editable=False, help_text='Unique 8-digit reference ID for display', null=True, unique=True),
        ),
    ]
