# Generated by Django 5.2.8 on 2026-04-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AliceTant', '0014_appointment_reference_id_business_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Whether the user account is suspended'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_at',
            field=models.DateTimeField(blank=True, help_text='When the user account was suspended', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Reason for suspending the user account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PROVIDER', 'Provider'), ('CUSTOMER', 'Customer'), ('ADMIN', 'Admin')], help_text="User's role in the system (PROVIDER, CUSTOMER, or ADMIN)", max_length=10),
        ),
    ]
