# Generated by Django 5.2.8 on 2026-04-27 03:09

import json

from django.db import migrations


def seed_system_settings(apps, schema_editor):
    SystemSetting = apps.get_model('AliceTant', 'SystemSetting')

    defaults = [
        ('max_appointment_duration_minutes', '480', 'int', 'Maximum appointment duration in minutes'),
        ('max_recurring_weeks', '64', 'int', 'Maximum recurring availability duration in weeks'),
        ('max_bookings_per_customer_per_day', '10', 'int', 'Maximum active bookings a customer can hold on one day'),
        ('announcement_banner_text', '', 'string', 'Announcement banner text'),
        ('announcement_banner_visible', 'false', 'bool', 'Whether the announcement banner is visible'),
        ('announcement_banner_severity', 'info', 'string', 'Announcement banner severity'),
    ]

    for key, value, value_type, description in defaults:
        SystemSetting.objects.update_or_create(
            key=key,
            defaults={
                'value': json.dumps(value) if value_type == 'json' else value,
                'value_type': value_type,
                'description': description,
            },
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('AliceTant', '0016_business_hidden_reason_business_is_hidden_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_system_settings, noop),
    ]
